version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - python_tp_DB__uri=postgresql://postgres:postgres@db:5432/python_tp
      - python_tp_DB__connect_args={}
    volumes:
      - .:/home/app/web
    depends_on:
      - db
  db:
    build: postgres
    image: python_tp_postgres-13-alpine-multi-user
    volumes:
      - $HOME/.postgres/python_tp_db/data/postgresql:/var/lib/postgresql/data
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DBS=python_tp, python_tp_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
